### ISSUE TITLE
[NIBR] "HTTP Error 409: Conflict" when refreshing metadata-api

### ISSUE THREAD

**Issue by chienhsiang** [dcic/signature-commons-controller#2]
Hi,

I just updated the metadata-api to 1.8.0. When I use the controller to refresh the metadata-api, I got the "HTTP Error 409: Conflict". However, I was able to use the API to refresh directly (/sigcom-metadata-api/summary/refresh). Is there anything I should change in the controller?

Here is the error message:
Traceback (most recent call last):
  File "sigcom.py", line 218, in <module>
    main()
  File "sigcom.py", line 214, in main
    getattr(sigcom, args.action)(**args.__dict__)
  File "sigcom.py", line 178, in refresh
    cli.main()
  File "/db/dmp/hsuchc/projects/sigcom/sigcom-controller/controller/cli.py", line 76, in main
    return getattr(router, args.action)(**args.__dict__)
  File "/db/dmp/hsuchc/projects/sigcom/sigcom-controller/controller/router.py", line 25, in action
    action.apply(**deepcopy(kwargs))
  File "/db/dmp/hsuchc/projects/sigcom/sigcom-controller/controller/action/meta/refresh_summary.py", line 35, in apply
    'Authorization': 'Basic {}'.format(metadata_token)
  File "/home/hsuchc/anaconda3/envs/sigcom/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/hsuchc/anaconda3/envs/sigcom/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/hsuchc/anaconda3/envs/sigcom/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/hsuchc/anaconda3/envs/sigcom/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/hsuchc/anaconda3/envs/sigcom/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/hsuchc/anaconda3/envs/sigcom/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 409: Conflict

Many thanks,
Charles

**Comment by u8sand** [comment]
@chienhsiang The conflict message just means a refresh/optimize operation was already running, it's likely that the controller tries to refresh multiple things at once getting the conflict, but I should at least be reporting the message that is returned by the API, which tells you that an operation is already happening.

Thanks for the report, will investigate and update it to poll the API before continuing.

FYI, you can use the `/summary/status` endpoint to see the current operation.

**Comment by chienhsiang** [comment]
Thank you so much for the quick response. It's working nicely!
